services:
  - type: web
    name: travel-concierge-api
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GOOGLE_CLOUD_LOCATION
        value: us-central1
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: GOOGLE_CLOUD_STORAGE_BUCKET
        sync: false
      - key: GOOGLE_GENAI_USE_VERTEXAI
        value: "0"
      - key: TRAVEL_CONCIERGE_SCENARIO
        value: travel_concierge/profiles/itinerary_empty_default.json
      - key: ENVIRONMENT
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
